package com.yoloo.server.user.exception

object UserErrors {
    const val NOT_FOUND = "user.not_found"
}
