package com.yoloo.server.user.exception

object UserErrors {
    const val ERROR_USER_NOT_FOUND = "user.not_found"
}